### ISSUE TITLE
Icons won't show up on other themes other than default.

### ISSUE THREAD

**Issue by Xeon3D** [vintagedaddyo/MyBB_Plugin-ForumsIcons#1]
Hi. 

I've properly set up the icons but they only show up on the default theme in latest mybb.

I've looked into the instructions and can't find out how to add them to the other themes?

**Comment by vintagedaddyo** [comment]
That is because some custom themes may have custom forumbit templates and those need to be reverted to default forumbit_depth1_cat, forumbit_depth2_forum, etc,etc, before plugin install. This is not a bug.
